spring.application.name=metro-ride-hybrid
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/metro_ride
spring.datasource.username=metro
spring.datasource.password=metro
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://localhost:27017/metro_ride
spring.data.mongodb.database=metro_ride

spring.sql.init.mode=never
